### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Kingorgg** [Kingorgg/mars#1]
**General**
- [ ] Update all functions to use language files (`$this->language->get()`), instead of strings of text. There is an example in `app/Controllers/AuthController`.
- [ ] Add more language support.

**Roleplays**
- [ ] Create an admin section for Roleplays.
- - [ ] Add and Remove Genders, per Roleplay.
- - [ ] Add and Remove Positions, per Roleplay.
- - [ ] View pending user's character applications and accept/deny.
- - [ ] View Roleplay Stats, like how many posts per month, etc.
- - [ ] Update Roleplay MOTD.
- [ ] Add an RSS Feed for posts.
- [ ] Add a Parent-Child Tree of Posts below a post, showing what a post is in reply to and links to view said posts.

**Site**
- [ ] Create a general site admin section.
- [ ] Create a user's profile view, with post history, signed up roleplays and all characters a player has.
- [ ] Create a Private Messaging section.
- [ ] Finish Adding a News/Blog area.
- - [ ] Also allow users to comment on posts in this area.
